---
title: "Task 1.5.1"
output: html_document
date: "2025-12-12"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
add_pvalue_block <- function(
  p,
  x,
  y,
  n,
  p1,
  p2,
  label1 = "p",
  label2 = "p",
  col_n  = "black",
  col_p1 = "deepskyblue3",
  col_p2 = "darkgoldenrod1",
  size   = NULL,
  line_gap = 0.04
) {

  if (is.null(size)) {
    th <- ggplot2::theme_get()
    size <- th$text$size %||% 11
  }

  yr <- ggplot2::layer_scales(p)$y$range$range
  dy <- diff(yr) * line_gap

  p +
    annotate(
      "text",
      x = x, y = y + dy,
      label = paste0("bolditalic(n == ", n, ")"),
      parse = TRUE,
      color = col_n
    ) +
    annotate(
      "text",
      x = x, y = y,
      label = paste0(
        "italic(p) == ", p1
      ),
      parse = TRUE,
      color = col_p1
    ) +
    annotate(
      "text",
      x = x, y = y - dy,
      label = paste0(
        "italic(p) == ", p2
      ),
      parse = TRUE,
      color = col_p2
    )
}
```

```{r}
summary(lm(data = data, snMultiome_RNA_mean_reads_per_cell ~ PMI))
cor.test(data$PMI, data$snMultiome_RNA_mean_reads_per_cell)
```

```{r}
pmi_multirna_ctrl = lm(snMultiome_RNA_mean_reads_per_cell ~ PMI, data = subset(data, Group == "CTRL"))
pmi_multirna_mdd = lm(snMultiome_RNA_mean_reads_per_cell ~ PMI, data = subset(data, Group == "MDD"))
summary(pmi_multirna_ctrl)
summary(pmi_multirna_mdd)
```

```{r}
p_pmi_multirna = ggplot(data, aes(x = PMI, y = snMultiome_RNA_mean_reads_per_cell, fill = Group, shape = Brain_Bank_Location, color = Group)) +
  geom_point(size = 5, stroke = 0.8, alpha = 0.8) +
  geom_abline(intercept = 76125.7, slope = 447.5, color = "deepskyblue3") +
  geom_abline(intercept = 114433, slope = -1812, color = "darkgoldenrod1") +
  scale_x_continuous(
    limits = c(0, 65),        
    breaks = seq(20, 60, 20)    
  ) + 
  scale_y_continuous(
    labels = label_number(scale = 1e-3, suffix = "k"),
    limits = c(0, 500000)        
  ) +
  scale_shape_manual(name = "Collection Location", values = c(21, 22)) +
  scale_fill_manual(values = c("deepskyblue3", "darkgoldenrod1")) +
  scale_color_manual(values=c("deepskyblue4","saddlebrown"), guide = "none") +
  labs(y = "AVG RNA reads") +
  guides(
  fill = guide_legend(
    order = 1,
    direction = "horizontal",
    override.aes = list(
      shape = 21,
      fill  = c("darkgoldenrod1", "deepskyblue3")
    ))
) +
  theme(
    text = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        axis.line = element_line(),
        panel.background = element_rect(fill='white'),
        plot.background = element_rect(fill='white', color=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.box = "vertical",
        legend.key.size = unit(0.3, "cm"),       # shrink legend key box
        legend.key.height = unit(0.3, "cm"),     # shrink height
        legend.spacing.x = unit(0.2, "cm"),      # reduce horizontal spacing
        plot.title = element_text(face = "bold", hjust = 0.5),
        plot.subtitle = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold",
                                    margin = margin(t = 2)),
        axis.title.y = element_text(face = "bold",
                                    margin = margin(r = 2)),
        axis.text.x = element_text(face = "bold",
                                   size = 24),
        axis.text.y = element_text(face = "bold",
                                   size = 24),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold"))
p_pmi_multirna<- add_pvalue_block(
  p_pmi_multirna,
  x = 50,
  y = 475000,
  n  = 74,
  p1 = "0.58",
  p2 = "0.37"
)
p_pmi_multirna
```

```{r}
summary(lm(data = data, snMultiome_RNA_mean_reads_per_cell ~ RIN))
cor.test(data$RIN, data$snMultiome_RNA_mean_reads_per_cell)
```

```{r}
rin_multirna_ctrl = lm(snMultiome_RNA_mean_reads_per_cell ~ RIN, data = subset(data, Group == "CTRL"))
rin_multirna_mdd = lm(snMultiome_RNA_mean_reads_per_cell ~ RIN, data = subset(data, Group == "MDD"))
summary(rin_multirna_ctrl)
summary(rin_multirna_mdd)
```

```{r}
p_rin_multirna = ggplot(data, aes(x = RIN, y = snMultiome_RNA_mean_reads_per_cell, fill = Group, shape = Brain_Bank_Location, color = Group)) +
  geom_point(size = 5, stroke = 0.8, alpha = 0.8) +
  geom_abline(intercept = 239565, slope = -20760, color = "deepskyblue3") +
  geom_abline(intercept = 121696, slope = -4221, color = "darkgoldenrod1") +
  scale_x_continuous(
    limits = c(5.5, 8.75),        
    breaks = seq(6, 8, 1)    
  ) + 
  scale_y_continuous(
    labels = label_number(scale = 1e-3, suffix = "k"),
    limits = c(0, 500000)       
  ) +
  scale_shape_manual(name = "Collection Location", values = c(21, 22)) +
  scale_fill_manual(values = c("deepskyblue3", "darkgoldenrod1")) +
  scale_color_manual(values=c("deepskyblue4","saddlebrown"), guide = "none") +
  labs(y = "AVG RNA reads") +
  guides(
  fill = guide_legend(
    order = 1,
    direction = "horizontal",   
    override.aes = list(
      shape = 21,
      fill  = c("darkgoldenrod1", "deepskyblue3")
    ))
) +
  theme(
    text = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        axis.line = element_line(),
        panel.background = element_rect(fill='white'),
        plot.background = element_rect(fill='white', color=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.box = "vertical",
        legend.key.size = unit(0.3, "cm"),       # shrink legend key box
        legend.key.height = unit(0.3, "cm"),     # shrink height
        legend.spacing.x = unit(0.2, "cm"),      # reduce horizontal spacing
        plot.title = element_text(face = "bold", hjust = 0.5),
        plot.subtitle = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold",
                                    margin = margin(t = 2)),
        axis.title.y = element_text(face = "bold",
                                    margin = margin(r = 2)),
        axis.text.x = element_text(face = "bold",
                                   size = 24),
        axis.text.y = element_text(face = "bold",
                                   size = 24),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold"))
p_rin_multirna<- add_pvalue_block(
  p_rin_multirna,
  x = 6.25,
  y = 475000,
  n  = 74,
  p1 = "0.10",
  p2 = "0.93"
)
p_rin_multirna
```

```{r}
ggsave("final_graph/1.5.1 PMI vs snMultiome_RNA_mean_reads_per_cell mdd vs ctrl 3.pdf", p_pmi_multirna, dpi = 72, width = 4, height = 4)
ggsave("final_graph/1.5.1 RIN vs snMultiome_RNA_mean_reads_per_cell mdd vs ctrl 3.pdf", p_rin_multirna, dpi = 72, width = 4, height = 4)
```

