#################
#Annotate Gene Lists for Visium v1 and v2 Differential  Enrichment Tables with KEGG and Reactome Pathways Associated With Each Gene
# Requires "[v1 or v2]_gene_differential_enrichment_batch_effect_with_ncbi_uniprot_date.xlsx" sheet from visium_differential_enrichment_ncbi_and_uniprot_naming.R
#By Victor Anosike
#Adapted from code by Lucia Polizzi
#################

import requests
import pandas as pd
import time
import gseapy as gp



###### Read input .xlsx file (from either v1 or v2) generated by visium_differential_enrichment_ncbi_and_uniprot_naming.R  ###########

input_file = "/path/to/[v1 or v2]_gene_differential_enrichment_batch_effect_with_ncbi_uniprot_date.xlsx"
df = pd.read_excel(input_file)

########### KEEG ####################
########### KEEG ####################
########### KEEG ####################

# ---------------------------
# KEGG flat-file parser
# ---------------------------
def parse_kegg_flat(text):
    data = {}
    current_key = None
    
    for line in text.splitlines():
        if line.strip() == "///":
            break

        key = line[:12].strip()
        value = line[12:].strip()

        if key:
            current_key = key
            if current_key in data:
                if isinstance(data[current_key], list):
                    data[current_key].append(value)
                else:
                    data[current_key] = [data[current_key], value]
            else:
                data[current_key] = value
        else:
            if current_key:
                if isinstance(data[current_key], list):
                    data[current_key][-1] += " " + value
                else:
                    data[current_key] += " " + value
    
    return data


# ---------------------------
# Get KEGG data for one gene
# ---------------------------
def get_kegg_info(gene_id):
    url = f"https://rest.kegg.jp/get/{gene_id}"
    
    try:
        r = requests.get(url, timeout=10)
        if not r.ok:
            return None
        return parse_kegg_flat(r.text)
    except Exception:
        return None


# ---------------------------
# Brain keyword list
# ---------------------------
BRAIN_KEYWORDS = [
    "neurogenesis", "neuron", "neuronal", "neurodevelopment", "neurotransmitter",
    "synap", "axon", "dendrit", "myelin", "gliogenesis", "glia", "astrocyte",
    "oligodendro", "microglia", "brain", "cortex", "cortical", "hippocamp",
    "cerebell", "cerebral", "nervous system", "neuroplastic", "learning", "memory"
]


# ---------------------------
# Extract pathway/disease info
# ---------------------------
def extract_info(parsed):
    if parsed is None:
        return "", "", ""

    # ---------- ALL PATHWAYS ----------
    pathways = parsed.get("PATHWAY", "")
    if isinstance(pathways, list):
        pathways_all = "; ".join(pathways)
    else:
        pathways_all = pathways

    # ---------- BRAIN FILTERED PATHWAYS ----------
    def filter_keywords(text):
        return "; ".join([x for x in text.split("; ") if any(k.lower() in x.lower() for k in BRAIN_KEYWORDS)])

    pathways_brain = filter_keywords(pathways_all)

    # ---------- BRAIN DISEASES ----------
    diseases = parsed.get("DISEASE", "")
    if isinstance(diseases, list):
        diseases_text = "; ".join(diseases)
    else:
        diseases_text = diseases

    diseases_brain = filter_keywords(diseases_text)

    return pathways_all, pathways_brain, diseases_brain


# ---------------------------
# MAIN PIPELINE
# ---------------------------


df.rename(columns=lambda x: x.strip(), inplace=True)

# Detect gene column
gene_column = "GeneID"
if gene_column not in df.columns:
    gene_column = df.columns[0]

# Add new columns
df["KEGG_Pathways_All"] = ""
df["KEGG_Pathways_Brain"] = ""
df["KEGG_Diseases_Brain"] = ""

# Loop through genes
for i, gene in enumerate(df[gene_column]):
    kegg_id = f"hsa:{gene}"

    parsed = get_kegg_info(kegg_id)
    pathways_all, pathways_brain, diseases_brain = extract_info(parsed)

    df.at[i, "KEGG_Pathways_All"] = pathways_all
    df.at[i, "KEGG_Pathways_Brain"] = pathways_brain
    df.at[i, "KEGG_Diseases_Brain"] = diseases_brain

    time.sleep(0.15)

    if i % 500 == 0:
        print(f"Processed {i} genes...")


########### REACTOME ###################
########### REACTOME ###################
########### REACTOME ###################

# Identify the gene column (case-insensitive)
gene_col = None
for col in df.columns:
    if col.lower() == "gene":
        gene_col = col
        break
if gene_col is None:
    raise ValueError("No column named 'Gene' found in your input file.")

# Extract gene list, unique, uppercase (for consistency)
genes = df[gene_col].dropna().astype(str).str.upper().unique().tolist()

# ------------------------------
# 2. Run Reactome enrichment via gseapy
# ------------------------------
# Use Reactome 2022 gene set library (or latest available)
enr = gp.enrichr(gene_list=genes,
                 gene_sets='Reactome_2022',  # or 'Reactome_2016', as available
                 organism='Human',
                 outdir=None,           # do not write default output files
                 no_plot=True)

res = enr.results  # pandas DataFrame

# If no enrichment found, warn
if res.empty:
    print("No pathways enriched for your gene list. Exiting.")
    exit()

# ------------------------------
# 3. Build pathway-level Excel
# ------------------------------
# The 'Genes' column contains overlapping genes separated by ";"
pathway_df = res.rename(columns={
    'Term': 'pathway_name',
    'Overlap': 'overlap',  # e.g. "5/450"
    'Adjusted P-value': 'FDR',
    'P-value': 'p_value',
    'Genes': 'found_genes'
})

# You may optionally parse overlap into found/total/ratio
def parse_overlap(x):
    try:
        a, b = x.split('/')
        return int(a), int(b), int(a)/int(b)
    except:
        return None, None, None

pathway_df[['entities_found','entities_total','entities_ratio']] = pathway_df['overlap'].apply(
    lambda x: pd.Series(parse_overlap(x))
)

# Reorder / select columns
pathway_df = pathway_df[[
    'pathway_name',
    'entities_found',
    'entities_total',
    'entities_ratio',
    'p_value',
    'FDR',
    'found_genes'
]]

# Save Excel Sheet with List of All Pathways and their Associated Genes
pathway_df.to_excel("/path/to/[v1 or v2]_gene_differential_enrichment_batch_effect_gseapy_pathways.xlsx", index=False)

# ------------------------------
# 4. Build gene-level table with pathway assignments
# ------------------------------
# Expand the found_genes per pathway to build gene-to-pathways mapping
gene_to_pathways = {}
for _, row in pathway_df.iterrows():
    pname = row['pathway_name']
    for g in str(row['found_genes']).split(';'):
        g = g.strip().upper()
        if g:
            gene_to_pathways.setdefault(g, []).append(pname)

# Add Pathway Name column to original df
def get_pathways_for_gene(gene):
    return ";".join(gene_to_pathways.get(str(gene).upper(), []))

df['Reactome Pathway Name'] = df[gene_col].apply(get_pathways_for_gene)

# Save Fully Annotated Differential Enrichment Excel Sheet
df.to_excel("/path/to/[v1 or v2]_gene_differential_enrichment_batch_effect_fully_annotated.xlsx", index=False)

print("➡️ Saved files:")
print("   • reactome_pathways_gseapy.xlsx")
print("   • reactome_genes_with_pathways_gseapy.xlsx")









