---
title: "Task 1.4.10"
output: html_document
date: "2025-12-15"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(scales)
library(readxl)
```

```{r}
wilcox.test(
  `Brain pH` ~ Group,
  data = ST1 %>%
  mutate(
    `Brain pH` = ifelse(`Brain pH` == "Unknown", NA, `Brain pH`),
    `Brain pH` = as.numeric(`Brain pH`)
  ),
  exact = FALSE
)
```

```{r}
p_box_pH = ggplot(ST1 %>%
  mutate(
    `Brain pH` = ifelse(`Brain pH` == "Unknown", NA, `Brain pH`),
    `Brain pH` = as.numeric(`Brain pH`)
  ), aes(x = Group, y = `Brain pH`, fill = Group, color = Group)) +
  geom_boxplot(aes(group = Group), fill = "white", color = "black", outlier.shape = NA) +
  geom_jitter(aes(fill = Group, shape = Brain_Bank_Location), size = 5, stroke = 0.8, alpha = 0.8) +
  scale_y_continuous(limits = c(NA, 7.2)) +
  annotate("text", x = 1, y = 7.15, label= "atop(bolditalic('Wilcoxon p'==0.73), bolditalic('n'==108))", parse = TRUE) +
  scale_shape_manual(name = "Collection Location", values = c(21, 24, 22)) +
  scale_fill_manual(values = c("deepskyblue3", "darkgoldenrod1")) +
  scale_color_manual(values=c("deepskyblue4","saddlebrown"), guide = "none") +
  labs(y = "Brain pH",
       x = NULL) +
  guides(
  fill = guide_legend(
    order = 1,
    direction = "horizontal",  
    override.aes = list(
      shape = 21,
      fill  = c("darkgoldenrod1", "deepskyblue3")
    ))
) +
  theme(
    text = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        axis.line = element_line(),
        panel.background = element_rect(fill='white'),
        plot.background = element_rect(fill='white', color=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "top",
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.box = "vertical",
        legend.key.size = unit(0.3, "cm"),       
        legend.key.height = unit(0.3, "cm"),     
        legend.spacing.x = unit(0.2, "cm"),      
        plot.title = element_text(face = "bold", hjust = 0.5),
        plot.subtitle = element_text(face = "bold", hjust = 0.5),
        axis.title.x = element_text(face = "bold",
                                    margin = margin(t = 2)),
        axis.title.y = element_text(face = "bold",
                                    margin = margin(r = 2)),
        axis.text.x = element_text(face = "bold",
                                   size = 24),
        axis.text.y = element_text(face = "bold",
                                   size = 24),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(legend.position = "none")
p_box_pH
```

```{r}
ggsave("final_graph/boxplot_Brain_ph MDD vs CTRL.pdf", p_box_pH, dpi = 72, width = 4, height = 4)
```

